export const environment = {
  production: false,
  defaultLocale: 'pt',
  API_URL: 'http://irishml.hcrp.usp.br/nutricao-api/v1',
  INTEGRACAO_URL: 'http://irishml.hcrp.usp.br/integracaolegado-api',
  HC_URL: 'http://irishml.hcrp.usp.br/nutricaohc-api',
  urlPoliticas: 'http://irishml.hcrp.usp.br/sso-api/usuario/policies?intitutoId=',
  IrisIntegracaoPrescricao: 'http://10.165.101.19/hml/IrisIntegracaoPrescricao',
  urlMenuApi: 'http://irishml.hcrp.usp.br',
  urlMenu: 'http://irishml.hcrp.usp.br',
  RouteDefaultPage: '/menu',
  sessionStorageToken: 'access_token_iris',
  sessionHCToken: 'hc-token',
  authIssuer: 'http://irishml.hcrp.usp.br/ssoserver',
  authClientId: 'IRIS.Menu.Frontend',
  authRedirectUri: 'http://irishml.hcrp.usp.br/nutricao-api/signin-oidc',
  authPostLogoutRedirectUri: 'http://irishml.hcrp.usp.br/signout',
  urlChangePassword: "http://irishml.hcrp.usp.br/change-password",
  mock: false,
  target: 'http://irishml.hcrp.usp.br/nutricao-api',
  modalWidth: '900px',
  authScope: 'offline_access openid profile email IRIS.SSO.Integration.Api IRIS.Menu.Api IRIS.MidiaSocial.Api IRIS.Portaria.Api IRIS.TI.Api IRIS.Guarita.Api IRIS.Prescricao.Api IRIS.ControleLeito.Api IRIS.Recepcao.Api IRIS.PEP.Api IRIS.Nutricao.Api'
}
